import ProcessToCheckOut from "../../support/pageObject/ProcessToCheckOut"

describe('Process to Checkout on Magento', () => {
    beforeEach(() => {
        cy.visit('https://magento.softwaretestingboard.com/') //Access URL Magento
    })
    it.skipp('First time checkout Product', () => { //Note jika belum pernah melakukan checkout dan ada product di chart
        ProcessToCheckOut.SignIn()
        ProcessToCheckOut.InputEmail('citrahutajulu@gmail.com')
        ProcessToCheckOut.InputPass('QA in my life')
        ProcessToCheckOut.BtnLogin()
        cy.wait(6000)
        ProcessToCheckOut.BtnChart()
        ProcessToCheckOut.BtnCheckout1()
        cy.wait(6000)
        ProcessToCheckOut.Fill_Comp('PT. Danamon Indonesia')
        ProcessToCheckOut.Fill_Add1('Jl Sari Indah')
        ProcessToCheckOut.Fill_Add2('Ciracas Segar')
        ProcessToCheckOut.Fill_Add3('Ciracas')
        ProcessToCheckOut.Fill_City('Jakarta Timur')
        ProcessToCheckOut.Fill_Reg1('2')
        ProcessToCheckOut.Fill_Post('663215-12345')
        ProcessToCheckOut.Fill_Reg2('2')
        ProcessToCheckOut.Fill_Phone('081345679876')
        ProcessToCheckOut.Radio_Btn1()
        ProcessToCheckOut.Next_Btn()
        cy.wait(6000)
        ProcessToCheckOut.Pay_Btn()
        cy.contains('Thank you for your purchase!')
    })
    it('Have checked out before', () => { //Note jika sudah pernah melakukan checkout dan ada product di chart
        ProcessToCheckOut.SignIn()
        ProcessToCheckOut.InputEmail('citrahutajulu@gmail.com')
        ProcessToCheckOut.InputPass('QA in my life')
        ProcessToCheckOut.BtnLogin()
        cy.wait(6000)
        ProcessToCheckOut.BtnChart()
        ProcessToCheckOut.BtnCheckout1()
        cy.wait(10000)
        ProcessToCheckOut.Radio_Btn1()
        ProcessToCheckOut.Next_Btn()
        cy.wait(10000)
        ProcessToCheckOut.Pay_Btn()
        cy.contains('Thank you for your purchase!')
    })
})
